FROM ghcr.io/cirruslabs/android-sdk:36-ndk

ENV ANDROID_HOME=/opt/android-sdk-linux
ENV ANDROID_NDK_HOME=${ANDROID_HOME}/ndk/27.3.13750724

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      cmake \
      ninja-build \
      libx11-dev \
      pkg-config \
      wayland-protocols \
      libwayland-dev \
      libxinerama-dev \
      libxcursor-dev \
      libxkbcommon-dev \
      libxrandr-dev \
      libxi-dev && \
    rm -rf /var/lib/apt/lists/*
